POST http://localhost:3000/users/signup
content-type: application/json

{
    "name": "name",
    "email": "email@mail.com",
}

###

POST http://localhost:3000/users/set-password
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzFlOWIzNWE1NThlMGI1MTQ0OGE1OCIsImlhdCI6MTYwMTMwMDkzNSwiZXhwIjoxNjAxOTA1NzM1fQ.jBPZsdpgeSW6VeBrYPb-qWx_aeKPzZcUN9mPDdkJl_A",
    "password": "1234"
}

###

GET http://localhost:3000/users/login
content-type: application/json

{
    "email": "email@mail.com",
    "password": "1234"
}

###

POST http://localhost:3000/users/reset-password
content-type: application/json

{
    "email": "email@mail.com"
}

###

GET http://localhost:3000/users/set-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzFlOWIzNWE1NThlMGI1MTQ0OGE1OCIsImlhdCI6MTYwMTMwMDkzNSwiZXhwIjoxNjAxOTA1NzM1fQ.jBPZsdpgeSW6VeBrYPb-qWx_aeKPzZcUN9mPDdkJl_A

###

POST https://partitasmusic.herokuapp.com/users/login
content-type: application/json

{
    "email": "email@mail.com",
    "password": "1234"
}

###

GET http://localhost:3000/aphorism

###

POST http://localhost:3000/api/create-contributor
content-type: application/json
Authorization: {{$dotenv SESSION_SECRET}}

{
    "name": "Tywi Roberts",
    "sort": "Roberts",
    "picture": "roberts.jpg",
    "country": "UK",
    "contact": "https://www.tywihywel.com",
    "donate": "",
    "category": "individual",
    "path": "tywi-roberts"
}

###

POST http://localhost:3000/api/create-contribution
content-type: application/json
Authorization: {{$dotenv SESSION_SECRET}}

{
    "title": "Liberal Knowledge",
    "description": "Written for three to five guitars, July 2020.",
    "audio": "Tywi JH Roberts - Liberal Knowledge.mp3",
    "score": "Tywi JH Roberts - Liberal Knowledge - Score in C.pdf",
    "path": "tywi-roberts"
}