GET http://localhost:3001/users/login
content-type: application/json

{
    "email": "email@mail.com",
    "password": "1234"
}

###

POST http://localhost:3001/users/signup
content-type: application/json

{
    "name": "name",
    "email": "email@mail.com",
    "password": "123456",
}

###

POST http://localhost:3001/users/reset-password
content-type: application/json

{
    "email": "email@mail.com"
}

###

POST http://localhost:3001/users/set-password
content-type: application/json

{
    "token": "jwt",
    "password": "1234"
}

###

GET http://localhost:3001/api/aphorism

###

GET http://localhost:3001/api/get-contributors

###

GET http://localhost:3001/api/get-contributor/CONTRIBUTOR-PATH

###

POST http://localhost:3001/api/signin
content-type: application/json

{
    "username": "email@mail.com",
    "password": "123456"
}

###

POST http://localhost:3001/api/update-contributor/CONTRIBUTOR-PATH
x-access-token: jwt
content-type: application/json

{
    "name": "testName",
    "sortBy": "sortByTest",
    "country": "countryTest",
    "bio": "bioTest",
    "contact": "contactTest",
    "donate": "donateTest",
    "category": "individual"
}

###

GET http://localhost:3001/api/verifyToken
x-access-token: jwt

###

GET http://localhost:3001/api/get-pieces/CONTRIBUTOR-PATH

###

POST http://localhost:3001/api/create-contributor
x-access-token: jwt
content-type: application/json

{
    "name": "name",
    "sortBy": "sortBy",
    "country": "country",
    "bio": "bio",
    "contact": "contact",
    "donate": "donate",
    "category": "individual"
}

###

POST http://localhost:3001/api/create-piece/CONTRIBUTOR-PATH
x-access-token: jwt
content-type: application/json

{
    "title": "title",
    "description": "description"
}

###

POST http://localhost:3001/api/update-piece
x-access-token: jwt
content-type: application/json

{
    "id": "id",
    "title": "title",
    "description": "description"
}

###
