POST http://localhost:3000/users/signup
content-type: application/json

{
    "name": "name",
    "email": "email@mail.com",
}

###

POST http://localhost:3000/users/set-password
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzFlOWIzNWE1NThlMGI1MTQ0OGE1OCIsImlhdCI6MTYwMTMwMDkzNSwiZXhwIjoxNjAxOTA1NzM1fQ.jBPZsdpgeSW6VeBrYPb-qWx_aeKPzZcUN9mPDdkJl_A",
    "password": "1234"
}

###

GET http://localhost:3000/users/login
content-type: application/json

{
    "email": "email@mail.com",
    "password": "1234"
}

###

POST http://localhost:3000/users/reset-password
content-type: application/json

{
    "email": "email@mail.com"
}

###

GET http://localhost:3000/users/set-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzFlOWIzNWE1NThlMGI1MTQ0OGE1OCIsImlhdCI6MTYwMTMwMDkzNSwiZXhwIjoxNjAxOTA1NzM1fQ.jBPZsdpgeSW6VeBrYPb-qWx_aeKPzZcUN9mPDdkJl_A

###

POST https://partitasmusic.herokuapp.com/users/login
content-type: application/json

{
    "email": "email@mail.com",
    "password": "1234"
}

###

GET http://localhost:3000/aphorism

###

POST http://localhost:3000/api/create-contributor
content-type: application/json
Authorization: {{$dotenv SESSION_SECRET}}

{
    "name": "ZUM",
    "sort": "ZUM",
    "picture": "ZUM.jpg",
    "country": "Argentina/Japan",
    "contact": "https://www.zumguitars.com",
    "donate": "https://www.patreon.com/ZumGuitars",
    "category": "group",
    "path": "zum"
}

###

POST http://localhost:3000/api/create-contribution
content-type: application/json
Authorization: {{$dotenv SESSION_SECRET}}

{
    "title": "Broken Funk",
    "description": "Shinkuro Matsuura, Luciano Pietrafesa and Fumihito Hatano’s main driving force is in the “Funk-Prog” style. Check their website!",
    "audio": "Broken Funk.mp3",
    "score": "Broken Funk.pdf",
    "path": "zum"
}